src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\AnswerRepository;
use App\Repository\QuestionRepository;
use App\Service\UploadHelper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Sluggable\Util\Urlizer;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\MaxDepth;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass=QuestionRepository::class)
 */
class Question
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("main")
     * @Assert\NotBlank(message="Mon messsage d'erreur")
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     * @Gedmo\Slug(fields={"name"})
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     * @Groups("main")
     */
    private $question;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $askedAt;

    /**
     * @ORM\Column(type="integer")
     */
    private $votes = 0;

    /**
     * @ORM\OneToMany(targetEntity=Answer::class, mappedBy="question", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({ "createdAt" = "DESC" })
     */
    private $answers;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="question")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("main")
     * @MaxDepth(1)
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="questions")
     */
    private $tag;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @ORM\OneToMany(targetEntity=QuestionReference::class, mappedBy="question")
     */
    private $questionReferences;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
        $this->tag = new ArrayCollection();
        $this->questionReferences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getAskedAt(): ?\DateTimeInterface
    {
        return $this->askedAt;
    }

    public function setAskedAt(?\DateTimeInterface $askedAt): self
    {
        $this->askedAt = $askedAt;

        return $this;
    }

    public function isPublished(): bool
    {
        return $this->getAskedAt() !== null;
    }

    public function getVotes(): ?int
    {
        return $this->votes;
    }

    public function getVotesString(): string
    {
        $prefix = $this->getVotes() >= 0 ? "+" : "-";
        return sprintf('%s %d', $prefix, abs($this->getVotes()));
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    public function upVote(): self
    {
        $this->votes++;
        return $this;
    }

    public function downVote(): self
    {
        $this->votes--;
        return $this;
    }

    /**
     * @return Collection|Answer[]
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    /**
     * @return Collection
     */
    public function getApprovedAnswers(): Collection
    {
        return $this->answers->matching(AnswerRepository::createApprovedCriteria());
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTag(): Collection
    {
        return $this->tag;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tag->contains($tag)) {
            $this->tag[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tag->removeElement($tag);

        return $this;
    }

    /**
     * @Assert\Callback()
     */
    public function validate(ExecutionContextInterface $context)
    {
        if (strpos($this->getName(), 'Francis') !== false) {
            $context->buildViolation('On avait dit pas Francis !')
                ->atPath('name')
                ->addViolation();
        }
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getImagePath()
    {
        return $this->getImageFilename() === null ?
            UploadHelper::DEFAULT_IMAGE :
            UploadHelper::QUESTION_IMAGE . '/' . $this->getImageFilename();
    }

    /**
     * @return Collection|QuestionReference[]
     */
    public function getQuestionReferences(): Collection
    {
        return $this->questionReferences;
    }

    public function addQuestionReference(QuestionReference $questionReference): self
    {
        if (!$this->questionReferences->contains($questionReference)) {
            $this->questionReferences[] = $questionReference;
            $questionReference->setQuestion($this);
        }

        return $this;
    }

    public function removeQuestionReference(QuestionReference $questionReference): self
    {
        if ($this->questionReferences->removeElement($questionReference)) {
            // set the owning side to null (unless already changed)
            if ($questionReference->getQuestion() === $this) {
                $questionReference->setQuestion(null);
            }
        }

        return $this;
    }
}

src/Controller/QuestionController.php
<?php

namespace App\Controller;

use App\Entity\Question;
use App\Form\QuestionFormType;
use App\Repository\QuestionRepository;
use App\Service\UploadHelper;
use Doctrine\ORM\EntityManagerInterface;
use Gedmo\Sluggable\Util\Urlizer;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bridge\PsrHttpMessage\Factory\UploadedFile;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class QuestionController extends AbstractController
{
    /**
     * @Route("/", name="app_homepage")
     * @return Response
     */
    public function homepage(QuestionRepository $repository)
    {
        $questions = $repository->findAllAskedOrderByNewest();

        return $this->render('question/homepage.html.twig', [
            'questions' => $questions
        ]);
    }

    /**
     * @param QuestionRepository $repository
     * @return Response
     * @Route("/questions/list", name="app_question_list")
     */
    public function listAll(QuestionRepository $repository)
    {
        $questions = $repository->findBy([], ['createdAt' => 'DESC']);
        return $this->render('question/list.html.twig', [
            'questions' => $questions
        ]);
    }

    /**
     * @Route("/questions/new", name="app_question_new")
     * @IsGranted("ROLE_USER")
     */
    public function new(Request $request, EntityManagerInterface $em, UploadHelper $helper): Response
    {
        $emptyQuestion = new Question();
        $emptyQuestion->setUser($this->getUser());
        $form = $this->createForm(QuestionFormType::class, $emptyQuestion);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var $question Question */
            $question = $form->getData();

            // Toute ma logique d'upload
            $newFile = $form['imageFile']->getData();
            if ($newFile) {
                $fileName = $helper->uploadQuestionImage($newFile);
                $question->setImageFilename($fileName);
            }

            $em->persist($question);
            $em->flush();

            $this->addFlash('success', 'Bien joué, une nouvelle question');

            return $this->redirectToRoute('app_question_list');
        }

        return $this->render('question/new.html.twig', [
            'questionForm' => $form->createView(),
            'titre' => 'Create Question'
        ]);
    }

    /**
     * @Route("/questions/{slug}", name="app_show")
     */
    public function show(Question $question)
    {
        $answers = $question->getAnswers();

        return $this->render('question/show.html.twig', [
            'question' => $question
        ]);
    }

    /**
     * @Route("/questions/{slug}/vote", name="app_question_vote", methods="POST")
     * @return Response
     */
    public function questionVote(Question $question, Request $request, EntityManagerInterface $entityManager)
    {
        $vote = $request->request->get('vote');
        if ($vote === 'up') {
            $question->upVote();
        } elseif ($vote === 'down') {
            $question->downVote();
        }

        $entityManager->flush();

        return $this->redirectToRoute('app_show', [
            'slug' => $question->getSlug()
        ]);
    }

    /**
     * @Route("/questions/{id}/delete")
     */
    public function questionDelete($id, EntityManagerInterface $entityManager)
    {
        // getReference ne marche qu'avec un id
        $question = $entityManager->getReference(Question::class, $id);
        $entityManager->remove($question);
        $entityManager->flush();

        return $this->redirectToRoute('app_homepage');
    }

    /**
     * @Route("questions/{slug}/edit", name="app_question_edit")
     * @IsGranted("ROLE_ADMIN_QUESTION")
     */
    public function edit(Question $question, Request $request, EntityManagerInterface $em, UploadHelper $helper)
    {
        // Je passe ma question en second argument et mes options en 3ème
        $form = $this->createForm(QuestionFormType::class, $question, [
            'include_askedAt' => true
        ]);

        // Le reste ne change pas
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var $question Question */
            $question = $form->getData();

            // Toute ma logique d'upload
            $newFile = $form['imageFile']->getData();
            if ($newFile) {
                $fileName = $helper->uploadQuestionImage($newFile, $question->getImageFilename());
                $question->setImageFilename($fileName);
            }

            $em->persist($question);
            $em->flush();

            $this->addFlash('success', 'Bien joué, votre question est updatée');

            return $this->redirectToRoute('app_show', ['slug' => $question->getSlug()]);
        }

        return $this->render('question/new.html.twig', [
            'questionForm' => $form->createView(),
            'titre' => 'Edit Question'
        ]);
    }

    /**
     * @Route("/questions/test/upload", name="app_test_upload")
     */
    public function uploadTest(Request $request)
    {
        /** @var UploadedFile $newFile */
        $newFile = $request->files->get('image');
        $destination = $this->getParameter('kernel.project_dir') . '/public/uploads';
        $originalFileName = $newFile->getClientOriginalName();
        $baseFileName = pathinfo($originalFileName, PATHINFO_FILENAME);

        // Un nom de fichier URL Friendly
        $fileName = Urlizer::urlize($baseFileName) . '-' . uniqid() . '.' . $newFile->guessExtension();

        $newFile->move($destination, $fileName);

        return new Response('yeah gagné');
    }
}

templates/question/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-4">Vos questions</h1>
            <p class="col-md-8 fs-4">Et même des réponses à des questions auquelles vous n'avez pas encore pensé</p>
            <a href="{{ path('app_question_new') }}" class="btn btn-primary" type="button">Posez votre question</a>
        </div>
    </div>
    <div class="row">

        {% for question in questions %}

            <div class="col-12">
                <div class="shadow p-3 mb-5 bg-body rounded">
                    <div class="q-container p-4">
                        <div class="row">
                            <div class="col-2 text-center">
                                <img src="{{ asset(question.imagePath) | imagine_filter('square_thumb') }}" width="100"
                                     height="100"
                                     class="bd-placeholder-img rounded-circle" style="object-fit: cover">
                                <div class="d-block mt-3 vote-arrows">
                                    <a class="vote-up" href="#"><i class="far fa-arrow-alt-circle-up"></i></a>
                                    <a class="vote-down" href="#"><i class="far fa-arrow-alt-circle-down"></i></a>
                                </div>
                            </div>
                            <div class="col">
                                <a class="q-title" href="{{ path('app_show', { slug: question.slug }) }}"><h2>
                                        {{ question.name }}</h2></a>
                                <div>
                                    {% for tag in question.tag %}
                                        <span class="badge bg-secondary">{{ tag.name }}</span>
                                    {% endfor %}
                                </div>
                                <div class="q-display p-3">
                                    <i class="fa fa-quote-left mr-3"></i>
                                    <p class="d-inline">
                                        {{ question.question|markdown_cached }}
                                    </p>
                                    <p class="pt-4"><strong>--{{ question.user.firstName }}</strong>,
                                        <small>{{ question.askedAt|ago }}</small></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a class="btn btn-secondary w-100" href="{{ path('app_show', { slug: question.slug }) }}">
                        <i class="fa fa-magic magic-wand"></i> {{ question.approvedAnswers|length }} answers
                    </a>
                </div>
            </div>

        {% endfor %}

    </div>
{% endblock %}

templates/question/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="p-5 mb-4 bg-light rounded-3 d-flex justify-content-between">
        <div class="container-fluid py-5">
            <h1 class="display-4">Toutes nos questions</h1>
            <p class="col-md-8 fs-4">Une belle liste de {{ questions|length }} éléments au total</p>
        </div>

    </div>


    <ul class="list-group list-group-flush">
        {% for question in questions %}

            <li class="list-group-item clearfix">
                <p style="color: red">{{ question.published ? 'Published' : 'NOT PUBLISED' }} -- {{ question.user.firstName }}</p>
                <p>{{ question.user.firstName }} : {{ question.name }}</p>
            </li>
        {% endfor %}
    </ul>


{% endblock %}

{% block title %}Toutes les quesitons{% endblock %}

templates/question/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle question{% endblock %}

{% block body %}


    <div class="row">


        <div class="mx-auto col-md-8">
            <h2 class="text-center">{{ titre }}</h2>
            {{ form_start(questionForm) }}
            {{ form_row(questionForm.name) }}
            {{ form_row(questionForm.question) }}

            {% if questionForm.vars.data.imageFilename != null %}
                <div class="text-center">
                    <p>Image de la question</p>
                    <img src="{{ asset(questionForm.vars.data.imagePath) }}" width="150"
                         height="150"
                         class="bd-placeholder-img rounded-circle" style="object-fit: cover">
                </div>
            {% endif %}
            {{ form_row(questionForm.imageFile) }}

            {{ form_row(questionForm.askedAt) }}
            {{ form_row(questionForm.user) }}
            {{ form_row(questionForm.submit) }}
            {{ form_end(questionForm) }}
        </div>

        {% if questionForm.vars.data.id|default %}
            <div class="col-md-4">
                <h2 class="text-center">Upload References</h2>
                <form action="{{ path('app_upload_question_reference', {id: questionForm.vars.data.id}) }}"
                      method="post" enctype="multipart/form-data">
                    <div class="mb-3">
                        <input type="file" class="form-control" name="reference">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

                <ul class="list-group mt-5">
                    {% for reference in questionForm.vars.data.questionReferences %}
                        <li class="list-group-item">
                            <a href="{{ path('app_download_question_reference', {id: reference.id}) }}" target="_blank">
                                {{ reference.originalFilename }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

    </div>
{% endblock %}

templates/question/show.html.twig
{# J'indique de quel fichier j'hérite #}
{% extends 'base.html.twig' %}

{# j'utilise parent() #}
{% block title %}Question{% endblock %}

{# Puis quel block je remplace #}
{% block body %}
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">

            <img src="{{ asset(question.imagePath) | imagine_filter('square_thumb') }}"
                 class="bd-placeholder-img rounded-circle" width="140"
                 height="140" style="object-fit: cover">

            <h1 class="display-5 fw-bold">{{ question.name }}</h1>
            <a href="{{ path('app_question_edit', {slug: question.slug}) }}" class="btn btn-warning mb-3">Edit
                Question</a>

            <div class="mb-3">
                {% for tag in question.tag %}
                    <span class="badge bg-secondary">{{ tag.name }}</span>
                {% endfor %}
            </div>


            <figure>
                <blockquote class="blockquote">

                    {{ question.question|markdown_cached }}

                </blockquote>
                <figcaption class="blockquote-footer">
                    {{ question.user.firstName }}, <cite title="Source Title">{{ question.askedAt|ago }}</cite>
                </figcaption>
            </figure>

            <div class="col">
                <form action="{{ path('app_question_vote', { slug: question.slug }) }}" method="post">
                    <button class="badge bg-success" name="vote" value="up">vote up</button>
                    <button class="badge bg-danger" name="vote" value="down">vote down</button>
                    <span class="badge bg-secondary mx-3">{{ question.votesString }}</span>
                </form>
            </div>

            <h2 class="mb-3 mt-5">Il y a {{ question.approvedAnswers|length }} réponses</h2>
            <button class="btn btn-primary mb-5">Répondre</button>
            <ul class="list-group list-group-flush">
                {% for answer in question.approvedAnswers %}

                    <li class="list-group-item clearfix">
                        <small>{{ answer.createdAt|ago }} -- </small>{{ answer.user.firstName }} : {{ answer.content }}

                        <div class="col float-end js-vote">
                            <button class="badge bg-success js-vote-up" data-direction="up" data-id="{{ answer.id }}">
                                vote up
                            </button>
                            <button class="badge bg-danger js-vote-down" data-direction="down"
                                    data-id="{{ answer.id }}">vote down
                            </button>
                            <span class="badge bg-secondary mx-3 js-vote-total">{{ answer.votes }}</span>
                        </div>

                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/question_show.js') }}"></script>
{% endblock %}